version: '3.8'

services:
  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=master
      - MYSQL_DATABASE=near-restaurant
      - MYSQL_USER=tybUser
      - MYSQL_PASSWORD=M0n1sT@ug22
    ports:
      - "3306:3306"
    networks:
      back-network:
        ipv4_address: 172.192.0.2

  nodejs:
    build:
      context: .
      target: dev
    depends_on:
      - database
    volumes:
      - ./src/:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      back-network:
        ipv4_address: 172.192.0.3

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.192.0.0/16
